spring:
  datasource:
    url: jdbc:mysql://localhost:3306/rules_engine
    username: root
    password: levyteng952786

logging:
  level:
    root: info
    org.springframework.jdbc.core.JdbcTemplate: debug
