ruler:
  business-type: person
  engine-type: complete
  rule-scan-packages: info.lostred.ruler.test.rule
  domain-scan-packages: info.lostred.ruler.test.domain

logging:
  level:
    info.lostred.ruler.rule: debug
    info.lostred.ruler.engine: debug
    info.lostred.ruler.test.rule: debug

spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8