

logging:
  level:
    root: info
    com.ylzinfo.ruler.jdbc.JdbcUtils: debug

ruler:
  init-type: annotation
  default-business-type: user
  default-valid-class: com.ylzinfo.ruler.test.entity.User
  valid-config:
    table-name: ruler_valid_info
  rule-config:
    table-name: ruler_rule_info
    scan-base-packages: com.ylzinfo.ruler.rule
  rules-engine-config:
    type: complete

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/rules_engine
    username: rules_engine
    password: 123456
